crypto:
  coin: "cardano"
deployment:
  slack_token: "slack access token"
  slack_channel: "slack channel name"
  threshold: 0.05 # threshold value in euro, will send notification when price is above this value